sudo: false
language: c

matrix:
  include:
  - env: GHCVER=7.6.3 CABALVER=1.18 BACKEND=none
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.6.3
        - cabal-install-1.18
  # Disabled, see:
  # https://github.com/yesodweb/persistent/issues/460
  #- GHCVER=7.6.3 CABALVER=1.18 BACKEND=sqlite
  - env: GHCVER=7.6.3 CABALVER=1.18 BACKEND=zookeeper
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.6.3
        - cabal-install-1.18
  - env: GHCVER=7.6.3 CABALVER=1.18 BACKEND=mongodb
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.6.3
        - cabal-install-1.18
  - env: GHCVER=7.6.3 CABALVER=1.18 BACKEND=postgresql
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.6.3
        - cabal-install-1.18
  - env: GHCVER=7.6.3 CABALVER=1.18 BACKEND=mysql
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.6.3
        - cabal-install-1.18

  - env: GHCVER=7.8.4 CABALVER=1.18 BACKEND=none
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - cabal-install-1.18
  - env: GHCVER=7.8.4 CABALVER=1.18 BACKEND=sqlite
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - cabal-install-1.18
  - env: GHCVER=7.8.4 CABALVER=1.18 BACKEND=zookeeper
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - cabal-install-1.18
  - env: GHCVER=7.8.4 CABALVER=1.18 BACKEND=mongodb
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - cabal-install-1.18
  - env: GHCVER=7.8.4 CABALVER=1.18 BACKEND=postgresql
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - cabal-install-1.18
  - env: GHCVER=7.8.4 CABALVER=1.18 BACKEND=mysql
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - cabal-install-1.18

  - env: GHCVER=7.10.2 CABALVER=1.22 BACKEND=none
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
        - cabal-install-1.22
  - env: GHCVER=7.10.2 CABALVER=1.22 BACKEND=sqlite
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
        - cabal-install-1.22
  - env: GHCVER=7.10.2 CABALVER=1.22 BACKEND=zookeeper
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
        - cabal-install-1.22
  - env: GHCVER=7.10.2 CABALVER=1.22 BACKEND=mongodb
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
        - cabal-install-1.22
  - env: GHCVER=7.10.2 CABALVER=1.22 BACKEND=postgresql
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
        - cabal-install-1.22
  - env: GHCVER=7.10.2 CABALVER=1.22 BACKEND=mysql
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
        - cabal-install-1.22

  - env: GHCVER=head CABALVER=head BACKEND=none
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-head
        - cabal-install-head

  allow_failures:
  - env: GHCVER=head CABALVER=head BACKEND=none
  - env: GHCVER=7.6.3 CABALVER=1.18 BACKEND=zookeeper
  - env: GHCVER=7.8.4 CABALVER=1.18 BACKEND=zookeeper
  - env: GHCVER=7.10.2 CABALVER=1.22 BACKEND=zookeeper

addons:
  postgresql: "9.3"

services:
- mysql
- mongodb

before_install:
- travis_retry /opt/cabal/$CABALVER/bin/cabal update

script: travis/run.sh

cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
